package com.judahben149.spendr.utils

object Constants {

    const val CATEGORY_BOTTOM_SHEET = "CATEGORY_BOTTOM_SHEET"
    const val REMINDER_BOTTOM_SHEET = "REMINDER_BOTTOM_SHEET"
    const val NOTIFICATION_PERMISSION_DIALOG = "NOTIFICATION_PERMISSION_DIALOG"
    const val APP_DATABASE_NAME = "spendr_database"
    const val USER_NAME = "USER_NAME"

    //Tags
    const val DATE_PICKER_ADD_CASH_ENTRY = "DATE_PICKER_ADD_CASH_ENTRY"
    const val SETTINGS_FILE = "app_pref"
    const val IS_FIRST_LAUNCH = "is_first_launch"
    const val TIMBER_TAG = "TIMBER_TAG"
    const val SETTINGS_DIALOG = "SETTINGS_DIALOG"
    const val DIALOG_TYPE = "DIALOG_TYPE"
    const val SHARE_SHEET_BOTTOM_DIALOG = "SHARE_SHEET_BOTTOM_DIALOG"
    const val EXPORT_BUDGET_DIALOG = "EXPORT_BUDGET_DIALOG"
    const val DELETE_ENTRY_DIALOG = "DELETE_ENTRY_DIALOG"
    const val GRANT_SMS_PERMISSION_DIALOG = "GRANT_SMS_PERMISSION_DIALOG"
    const val DIALOG_TITLE = "DIALOG_TITLE"
    const val DIALOG_BODY = "DIALOG_BODY"
    const val DIALOG_POSITIVE_BUTTON = "DIALOG_POSITIVE_BUTTON"
    const val DIALOG_NEGATIVE_BUTTON = "DIALOG_NEGATIVE_BUTTON"
    const val ENTER_TEXT_MODE = "ENTER_TEXT_MODE"
    const val DIALOG_REQUEST_CODE = "DIALOG_REQUEST_CODE"

    //Flags
    const val SHOULD_SHOW_TOOL_BAR = "SHOULD_SHOW_TOOL_BAR"

    //Keys
    const val IS_INCOME_ENTRY_TYPE = "IS_INCOME_ENTRY_TYPE"
    const val ENTRY_ID = "ENTRY_ID"
    const val ENTRY_DETAIL_ID = "ENTRY_DETAIL_ID"
    const val REMINDER_TITLE = "REMINDER_TITLE"
    const val REMINDER_TEXT = "REMINDER_TEXT"
    const val NOTIFICATION_BUNDLE = "NOTIFICATION_BUNDLE"
    const val KEY_BALANCE_HIDDEN_STATE = "KEY_BALANCE_HIDDEN_STATE"
    const val RECEIVE_SMS_ENTRIES = "RECEIVE_SMS_ENTRIES"

    const val ONBOARDING_FRAGMENT_PAGE = "ONBOARDING_FRAGMENT_PAGE"

    //Constants
    const val INITIAL_PAGE = 0
    const val PAGE_SIZE = 20
    const val PREFETCH_DISTANCE = 5
    const val INITIAL_LOAD_SIZE = 20
}