package com.judahben149.spendr.utils

import android.content.Context
import androidx.preference.PreferenceManager
import javax.inject.Inject

class CurrencyUtils @Inject constructor() {

    fun getCurrencySymbol(context: Context): String {
        val prefs = PreferenceManager.getDefaultSharedPreferences(context)

        return when(prefs.getString("currency", "Nigerian Naira (₦)")) {
            "Afghan Afghani (؋)" -> "؋"
            "Albanian Lek (Lek)" -> "Lek"
            "Algerian Dinar (د.ج)" -> "د.ج"
            "American Dollar ($)" -> "$"
            "Angolan Kwanza (Kz)" -> "Kz"
            "Argentine Peso ($)" -> "$"
            "Armenian Dram (֏)" -> "֏"
            "Aruban Florin (ƒ)" -> "ƒ"
            "Australian Dollar ($)" -> "$"
            "Azerbaijani Manat (₼)" -> "₼"
            "Bahamian Dollar ($)" -> "$"
            "Bahraini Dinar (ب.د)" -> "ب.د"
            "Bangladeshi Taka (৳)" -> "৳"
            "Barbadian Dollar ($)" -> "$"
            "Belarusian Ruble (Br)" -> "Br"
            "Belarusian Ruble (BYN)" -> "BYN"
            "Belizian Dollar ($)" -> "$"
            "Bermudian Dollar ($)" -> "$"
            "Bhutanese Ngultrum (Nu.)" -> "Nu."
            "Bolivian Boliviano (Bs.)" -> "Bs."
            "Bosnia and Herzegovina Convertible Mark (KM)" -> "KM"
            "Botswana Pula (P)" -> "P"
            "Brazilian Real (R$)" -> "R$"
            "British Pound (£)" -> "£"
            "Brunei Dollar ($)" -> "$"
            "Bulgarian Lev (лв)" -> "лв"
            "Burundian Franc (Fr)" -> "Fr"
            "Cambodian Riel (៛)" -> "៛"
            "Canadian Dollar ($)" -> "$"
            "Cape Verdean Escudo ($)" -> "$"
            "Cayman Islands Dollar ($)" -> "$"
            "Central African CFA Franc (Fr)" -> "Fr"
            "Chilean Peso ($)" -> "$"
            "Chinese Yuan (¥)" -> "¥"
            "Colombian Peso ($)" -> "$"
            "Comorian Franc (Fr)" -> "Fr"
            "Congolese Franc (Fr)" -> "Fr"
            "Costa Rican Colón (₡)" -> "₡"
            "Croatian Kuna (kn)" -> "kn"
            "Cuban Convertible Peso ($)" -> "$"
            "Cuban Peso (\$MN)" -> "\$MN"
            "Czech Koruna (Kč)" -> "Kč"
            "Danish Krone (kr)" -> "kr"
            "Djiboutian Franc (Fr)" -> "Fr"
            "Dominican Peso (RD$)" -> "RD$"
            "East Caribbean Dollar ($)" -> "$"
            "Egyptian Pound (ج.م)" -> "ج.م"
            "Equatorial Guinean CFA Franc (Fr)" -> "Fr"
            "Eritrean Nakfa (Nfk)" -> "Nfk"
            "Estonian Euro (€)" -> "€"
            "Eswatini Lilangeni (L)" -> "L"
            "Ethiopian Birr (Br)" -> "Br"
            "Euro (€)" -> "€"
            "Falkland Islands Pound (£)" -> "£"
            "Fijian Dollar ($)" -> "$"
            "Gambian Dalasi (D)" -> "D"
            "Georgian Lari (₾)" -> "₾"
            "Ghanaian Cedi (₵)" -> "₵"
            "Gibraltar Pound (£)" -> "£"
            "Guatemalan Quetzal (Q)" -> "Q"
            "Guernsey Pound (£)" -> "£"
            "Guinean Franc (Fr)" -> "Fr"
            "Guinean Syli (₣)" -> "₣"
            "Guyanese Dollar ($)" -> "$"
            "Haitian Gourde (G)" -> "G"
            "Honduran Lempira (L)" -> "L"
            "Hong Kong Dollar ($)" -> "$"
            "Hungarian Forint (Ft)" -> "Ft"
            "Icelandic Króna (kr)" -> "kr"
            "Indian Rupee (₹)" -> "₹"
            "Indonesian Rupiah (Rp)" -> "Rp"
            "Iranian Rial (﷼)" -> "﷼"
            "Iraqi Dinar (ع.د)" -> "ع.د"
            "Israeli Shekel (₪)" -> "₪"
            "Italian Euro (€)" -> "€"
            "Jamaican Dollar ($)" -> "$"
            "Japanese Yen (¥)" -> "¥"
            "Jersey Pound (£)" -> "£"
            "Jordanian Dinar (د.ا)" -> "د.ا"
            "Kazakhstani Tenge (₸)" -> "₸"
            "Kenyan Shilling (KSh)" -> "KSh"
            "Kuwaiti Dinar (د.ك)" -> "د.ك"
            "Kyrgyzstani Som (сом)" -> "сом"
            "Laotian Kip (₭)" -> "₭"
            "Latvian Lats (Ls)" -> "Ls"
            "Lebanese Pound (ل.ل)" -> "ل.ل"
            "Lesotho Loti (L)" -> "L"
            "Liberian Dollar ($)" -> "$"
            "Libyan Dinar (ل.د)" -> "ل.د"
            "Lithuanian Litas (Lt)" -> "Lt"
            "Macanese Pataca (P)" -> "P"
            "Macedonian Denar (ден)" -> "ден"
            "Malagasy Ariary (Ar)" -> "Ar"
            "Malawian Kwacha (MK)" -> "MK"
            "Malaysian Ringgit (RM)" -> "RM"
            "Maldivian Rufiyaa (ރ)" -> "ރ"
            "Mauritanian Ouguiya (UM)" -> "UM"
            "Mauritian Rupee (₨)" -> "₨"
            "Mexican Peso ($)" -> "$"
            "Moldovan Leu (L)" -> "L"
            "Mongolian Tögrög (₮)" -> "₮"
            "Montenegrin Euro (€)" -> "€"
            "Montserratian Dollar ($)" -> "$"
            "Moroccan Dirham (د.م.)" -> "د.م."
            "Mozambican Metical (MT)" -> "MT"
            "Myanmar Kyat (K)" -> "K"
            "Namibian Dollar ($)" -> "$"
            "Nepalese Rupee (₨)" -> "₨"
            "Netherlands Antillean Guilder (ƒ)" -> "ƒ"
            "New Taiwan Dollar ($)" -> "$"
            "New Zealand Dollar ($)" -> "$"
            "Nicaraguan Córdoba (C$)" -> "C$"
            "Nigerian Naira (₦)" -> "₦"
            "North Korean Won (₩)" -> "₩"
            "Norwegian Krone (kr)" -> "kr"
            "Omani Rial (ر.ع.)" -> "ر.ع."
            "Pakistani Rupee (₨)" -> "₨"
            "Panamanian Balboa (B/.)" -> "B/."
            "Papua New Guinean Kina (K)" -> "K"
            "Paraguayan Guarani (₲)" -> "₲"
            "Peruvian Sol (S/.)" -> "S/."
            "Philippine Peso (₱)" -> "₱"
            "Polish Złoty (zł)" -> "zł"
            "Qatari Riyal (ر.ق)" -> "ر.ق"
            "Romanian Leu (lei)" -> "lei"
            "Russian Ruble (₽)" -> "₽"
            "Rwandan Franc (Fr)" -> "Fr"
            "Saint Helena Pound (£)" -> "£"
            "Saint Kitts and Nevis Dollar ($)" -> "$"
            "Saint Lucian Dollar ($)" -> "$"
            "Saint Martin Euro (€)" -> "€"
            "Saint Pierre and Miquelon Euro (€)" -> "€"
            "Saint Vincent and the Grenadines Dollar ($)" -> "$"
            "Samoan Tālā (T)" -> "T"
            "São Tomé and Príncipe Dobra (Db)" -> "Db"
            "Saudi Riyal (ر.س)" -> "ر.س"
            "Senegalese Franc (Fr)" -> "Fr"
            "Serbian Dinar (дин.)" -> "дин."
            "Seychellois Rupee (₨)" -> "₨"
            "Sierra Leonean Leone (Le)" -> "Le"
            "Singapore Dollar ($)" -> "$"
            "Slovak Euro (€)" -> "€"
            "Slovenian Euro (€)" -> "€"
            "Solomon Islands Dollar ($)" -> "$"
            "Somali Shilling (S)" -> "S"
            "South African Rand (R)" -> "R"
            "South Korean Won (₩)" -> "₩"
            "South Sudanese Pound (£)" -> "£"
            "Sri Lankan Rupee (₨)" -> "₨"
            "Sudanese Pound (ج.س.)" -> "ج.س."
            "Surinamese Dollar ($)" -> "$"
            "Swazi Lilangeni (L)" -> "L"
            "Swedish Krona (kr)" -> "kr"
            "Swiss Franc (Fr)" -> "Fr"
            "Syrian Pound (ل.س)" -> "ل.س"
            "Taiwan Dollar ($)" -> "$"
            "Tajikistani Somoni (ЅМ)" -> "ЅМ"
            "Tanzanian Shilling (Sh)" -> "Sh"
            "Thai Baht (฿)" -> "฿"
            "Tongan Paʻanga (T$)" -> "T$"
            "Trinidad and Tobago Dollar ($)" -> "$"
            "Tunisian Dinar (د.ت)" -> "د.ت"
            "Turkish Lira (₺)" -> "₺"
            "Turkmenistan Manat (m)" -> "m"
            "Tuvaluan Dollar ($)" -> "$"
            "Ugandan Shilling (Sh)" -> "Sh"
            "Ukrainian Hryvnia (₴)" -> "₴"
            "United Arab Emirates Dirham (د.إ)" -> "د.إ"
            "United States Dollar ($)" -> "$"
            "Uruguayan Peso (\$U)" -> "\$U"
            "Uzbekistani Som (so'm)" -> "so'm"
            "Vanuatu Vatu (Vt)" -> "Vt"
            "Venezuelan Bolívar (Bs.)" -> "Bs."
            "Vietnamese đồng (₫)" -> "₫"
            "Wallis and Futuna CFP Franc (Fr)" -> "Fr"
            "Yemeni Rial (﷼)" -> "﷼"
            "Zambian Kwacha (ZK)" -> "ZK"
            "Zimbabwean Dollar ($)" -> "$"
            else -> "₦"
        }
    }
}